# Generated by Django 3.2.9 on 2023-06-14 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(db_column='module_name', max_length=50)),
                ('moduleStyle', models.CharField(db_column='module_style', max_length=120)),
                ('url', models.CharField(db_column='url', max_length=100)),
                ('parentOptValue', models.CharField(db_column='parent_opt_value', max_length=20)),
                ('grade', models.IntegerField(db_column='grade')),
                ('optValue', models.CharField(db_column='opt_value', max_length=20)),
                ('orders', models.IntegerField(db_column='orders')),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('updateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', max_length=20)),
                ('parent', models.ForeignKey(db_column='parent_id', db_constraint=False, default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='system.module')),
            ],
            options={
                'db_table': 't_module',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aclValue', models.CharField(db_column='acl_value', max_length=20)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('updateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', max_length=20)),
                ('module', models.ForeignKey(db_column='module_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='system.module')),
            ],
            options={
                'db_table': 't_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(db_column='role_name', max_length=20)),
                ('roleRemark', models.CharField(db_column='role_remark', max_length=120)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('updateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', max_length=20)),
                ('permissions', models.ManyToManyField(through='system.Permission', to='system.Module')),
            ],
            options={
                'db_table': 't_role',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=4)),
                ('truename', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('state', models.IntegerField(default=0)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(db_column='create_date', default=datetime.datetime(2023, 6, 14, 16, 27, 56, 391986))),
                ('updateDate', models.DateTimeField(db_column='update_date', null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('updateDate', models.DateTimeField(auto_now_add=True, db_column='update_date', max_length=20)),
                ('role', models.ForeignKey(db_column='role_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='system.role')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='system.tuser')),
            ],
            options={
                'db_table': 't_user_role',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(db_column='role_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='system.role'),
        ),
    ]
