# Generated by Django 3.2.9 on 2023-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serveType', models.CharField(db_column='serve_type', max_length=50)),
                ('overview', models.CharField(db_column='overview', max_length=500)),
                ('customer', models.CharField(db_column='customer', max_length=30)),
                ('state', models.CharField(db_column='state', max_length=10)),
                ('serviceRequest', models.CharField(db_column='service_request', max_length=500)),
                ('createPeople', models.CharField(db_column='create_people', max_length=100)),
                ('assigner', models.CharField(db_column='assigner', max_length=100)),
                ('assignTime', models.DateTimeField(db_column='assign_time')),
                ('serviceProce', models.CharField(db_column='service_proce', max_length=500)),
                ('serviceProcePeople', models.CharField(db_column='service_proce_people', max_length=50)),
                ('serviceProceTime', models.DateTimeField(db_column='service_proce_time')),
                ('serviceProceResult', models.CharField(db_column='service_proce_result', max_length=500)),
                ('myd', models.CharField(db_column='myd', max_length=50)),
                ('isValid', models.IntegerField(db_column='is_valid', default=1)),
                ('createDate', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('updateDate', models.DateTimeField(auto_now_add=True, db_column='update_date')),
            ],
            options={
                'db_table': 't_customer_serve',
            },
        ),
    ]
